global:
  # scrape_interval is set to the global default (1 minute).
  # evaluation_interval is set to the global default (1 minute).
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "paas metrics"
    static_configs:
      - targets: [ "prometheus-exporter-dluhc-core.apps.internal:8080" ]

remote_read:
  - url: https://$INFLUXDB_SERVER/api/v1/prom/read?db=defaultdb
    basic_auth:
      username: $INFLUXDB_USER
      password: $INFLUXDB_PASSWORD

remote_write:
  - url: https://$INFLUXDB_SERVER/api/v1/prom/write?db=defaultdb
    basic_auth:
      username: $INFLUXDB_USER
      password: $INFLUXDB_PASSWORD
