name: Build Prometheus image

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE: communitiesuk/dluhc-data-collection-monitoring/prometheus

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate prometheus configuration
        run: make prometheus_config

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: '${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE }}:latest'
