name: Metrics exporter deployment on GOV.UK PaaS

on: workflow_dispatch

env:
  APP_NAME: prometheus-exporter

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monitoring repository
        uses: actions/checkout@v2

      - name: Checkout exporter repository
        uses: actions/checkout@v2
        with:
          repository: alphagov/paas-prometheus-exporter
          path: exporter

      - name: Install Cloud Foundry CLI
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf8-cli

      - name: Deploy Prometheus exporter to GOV.UK PaaS
        env:
          APP_NAME: ${{ env.APP_NAME }}
          CF_API_ENDPOINT: ${{ secrets.CF_API_ENDPOINT }}
          CF_ORG: ${{ secrets.CF_ORG }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
          CF_DEPLOY_USERNAME: ${{ secrets.CF_DEPLOY_USERNAME}}
          CF_DEPLOY_PASSWORD: ${{ secrets.CF_DEPLOY_PASSWORD }}
          CF_AUDIT_USERNAME: ${{ secrets.CF_AUDIT_USERNAME }}
          CF_AUDIT_PASSWORD: ${{ secrets.CF_AUDIT_PASSWORD }}
        run: |
          cf api $CF_API_ENDPOINT
          cf auth $CF_DEPLOY_USERNAME $CF_DEPLOY_PASSWORD
          cf target -o $CF_ORG -s $CF_SPACE
          cf push --no-start $APP_NAME -f manifest.yml -p exporter
          cf set-env $APP_NAME API_ENDPOINT "https://${CF_API_ENDPOINT}"
          cf set-env $APP_NAME USERNAME $CF_AUDIT_USERNAME
          cf set-env $APP_NAME PASSWORD $CF_AUDIT_PASSWORD
          cf push $APP_NAME -f manifest.yml -p exporter
