name: Grafana deployment on GOV.UK PaaS

on: workflow_dispatch

env:
  APP_NAME: grafana
  PRIVATE_APP_NAME: prometheus

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Cloud Foundry CLI
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf8-cli

      - name: Deploy Prometheus to GOV.UK PaaS
        env:
          APP_NAME: ${{ env.APP_NAME }}
          PRIVATE_APP_NAME: ${{ env.PRIVATE_APP_NAME }}
          CF_API_ENDPOINT: ${{ secrets.CF_API_ENDPOINT }}
          CF_ORG: ${{ secrets.CF_ORG }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
          CF_DEPLOY_USERNAME: ${{ secrets.CF_DEPLOY_USERNAME}}
          CF_DEPLOY_PASSWORD: ${{ secrets.CF_DEPLOY_PASSWORD }}
          GRAFANA_ADMIN_USERNAME: ${{ secrets.GRAFANA_ADMIN_USERNAME }}
          GRAFANA_ADMIN_PASSWORD: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
        run: |
          cf api $CF_API_ENDPOINT
          cf auth $CF_DEPLOY_USERNAME $CF_DEPLOY_PASSWORD
          cf target -o $CF_ORG -s $CF_SPACE
          cf push --no-start $APP_NAME
          cf set-env $APP_NAME GRAFANA_ADMIN_USERNAME $GRAFANA_ADMIN_USERNAME
          cf set-env $APP_NAME GRAFANA_ADMIN_PASSWORD $GRAFANA_ADMIN_PASSWORD
          cf add-network-policy $APP_NAME $PRIVATE_APP_NAME --protocol tcp --port 9090
          cf push $APP_NAME
